### ISSUE TITLE
Add fugitive support

### ISSUE THREAD

**Issue by petobens** [chemzqm/denite-git#1]
Can you consider adding fugitive support?

**Comment by chemzqm** [comment]
~~No, I think.  But you (or anyone else) could fork this repo and make it works with fugitive.
The reason I create vim-easygit is that I find fugitive's API is hard to use, and it's bad performance for vim startup time.~~

**Comment by chemzqm** [comment]
I tried but find out fugitive not providing some api I need (like show the diff content in a split buffer).
vim-easygit could works with fugitive, just not enable the commands.

**Comment by petobens** [comment]
Mmm but can you consider adding minimal support? Even though the api does't provide everything you need.
