### ISSUE TITLE
Add support for :DeniteBufferDir

### ISSUE THREAD

**Issue by skt041959** [chemzqm/denite-git#12]
Hi Developer,

Would you please add support for :DeniteBufferDir ? 
I found that this plugin will find git root from vim.eval('getcwd()'), which will forbid the usage of opening file from other directories.

Thanks

**Comment by chemzqm** [comment]
Sure, I will have a look at that.
I'm not having this problem since I'm using the auto lcd feature of https://github.com/neoclide/vim-easygit

**Comment by chemzqm** [comment]
Now, it's resolving git root from current buffer when possible.
