### ISSUE TITLE
gitstatus open action broken when opening vim somewhere other than git root

### ISSUE THREAD

**Issue by sodiumjoe** [chemzqm/denite-git#34]
repro:

```sh
$ pwd
/Users/moon/home/denite-git
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ cd rplugin
$ touch foo
$ nvim
```

Then in neovim `:Denite gitstatus` displays `rplugin/foo`. When you hit enter you get:

```
"rplugin" does not exist. Create? [yes/no]:
```

Started with this commit: https://github.com/neoclide/denite-git/commit/091e544a68feb9bd3063b791c04225bdd9efe1fc

**Comment by delphinus** [comment]
I cannot reproduce this. When with vimrc below, it successfully opens `gitstatus`.

```vim
set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/.config/nvim/after
set runtimepath+=~/test/denite.nvim
set runtimepath+=~/test/denite-git

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
endfunction
```

Can you provide minimal reproducible vimrc & your nvim version ?

[![asciicast](https://asciinema.org/a/374394.svg)](https://asciinema.org/a/374394)

**Comment by delphinus** [comment]
Ah!!! I understand it! Surely it broke `:Denite gitstatus` & “open it”. Sorry, I will fix it.

**Comment by delphinus** [comment]
I fixed (reverted) the logic to solve this. See #36 @sodiumjoe @chemzqm
