### ISSUE TITLE
`git add --patch` support in `gitstatus` source

### ISSUE THREAD

**Issue by neilvyas** [chemzqm/denite-git#4]
first, thanks for the awesome plugin.

The git workflow supported by `gitstatus` is almost my whole workflow. I just need it to have

- [x] `git add --patch`  
  I usually make many changes at once and then make a second pass at commit-time to separate those changes into multiple commit. Thus, the existing `add` action is too coarse for me, since it 
- [ ] `git rebase --interactive`
  I understand this source is more oriented towards working on your current working-tree rather than working on the index / mucking with commits, but interactively rebasing my feature branch from lots of atomic commits to just a few squashed and fixed up ones is something I always do before preparing a PR for deployment.

If you are already working on implementing this then I won't try. I will try to implement it myself and PR.

**Comment by neilvyas** [comment]
I think this is just out of scope, since it would basically mean fugitive integration, which you've already said you don't want to do.

**Comment by chemzqm** [comment]
`git add --patch`
could be implemented by split a terminal buffer, I will implement that.

`git rebase --interactive`
Looks like fugitive not have support for rebase command, use terminal would just be fine IMO.

**Comment by chemzqm** [comment]
I've added `patch` action for `git add --patch`, with multiply files support.
