### ISSUE TITLE
Folding gitlog:all

### ISSUE THREAD

**Issue by GordianDziwis** [chemzqm/denite-git#8]
I would like to fold the preview window, for a better overview when a commit is huge. I tried it unsuccessfully with:

```vim
" Folding
set foldmethod=syntax

autocmd FileType git set foldenable
autocmd FileType git set foldlevel=0
```

Any Ideas?

**Comment by chemzqm** [comment]
It should just works.
Try `set ft=git` and fold again.

**Comment by GordianDziwis** [comment]
Hm, I get this behavior too with an minimal vimrc. Everything up to date and nvim with version 0.2.2.
The ft is correctly set, but if I set it again then it folds.

**Comment by chemzqm** [comment]
@BonaBeavis 
How could you move cursor to preview window after press `p` on one of the git log?
Could you fold the contents after press `enter` on one of the git log?

**Comment by GordianDziwis** [comment]
Yes after pressing enter I could fold the commit.

**Comment by chemzqm** [comment]
Can't reproduce.
I've tried with a minimal .vimrc, and I could do fold and unfold in the preview window with the command `zi`

**Comment by GordianDziwis** [comment]
Sorry, I was not precise enough. When I preview `Denite gitlog:all`, I would prefer the preview to be *already* folded. So I can see, with a quick glance what files have been modified in a commit.

**Comment by chemzqm** [comment]
I disabled the fold since I didn't find the way to move cursor to preview window.
Now I made fold the default behaviour.

**Comment by GordianDziwis** [comment]
Nice, thanks!
